#!/bin/bash
#SBATCH --job-name=gcaRefactorGcav7_explicit_noevegradb_f1000
#SBATCH --account=f202500196cpcaa3a
#SBATCH --partition=normal-arm
#SBATCH --time=0-00:20:00
#SBATCH --nodes=1
#SBATCH --ntasks=8

module purge
module load OpenMPI
ml HDF5/1.12.2-gompi-2022a
module load FFTW

# ---- choose branch here ----
BRANCH="deucalion_gca"
WTBASE="$HOME/osiris_worktrees"

WORKTREE="$WTBASE/deucalion_gca"

# ---- executable + input ----
EXE="osiris-3D-${BRANCH}.e"
BIN="$WORKTREE/bin/$EXE"
INPUT="Gcav7_explicit_noevegradb_f.in"

srun "$BIN" "$INPUT"
