#!/bin/bash
#SBATCH --job-name=Curv1stepgcaNoDrifts_doublePrecDiag_and_Gca_maxIter10000_001
#SBATCH --account=f202500196cpcaa3a
#SBATCH --partition=normal-arm
#SBATCH --time=0-24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=8

module purge
module load OpenMPI
ml HDF5/1.12.2-gompi-2022a
module load FFTW

# ---- choose branch here ----
BRANCH="gcaNoDrifts_doublePrecDiag_and_Gca_maxIter1000"
WTBASE="$HOME/osiris_worktrees"

WORKTREE="$WTBASE/gcaNoDrifts_doublePrecDiag_and_Gca"

# ---- executable + input ----
EXE="osiris-3D-${BRANCH}.e"
BIN="$WORKTREE/bin/$EXE"
INPUT="gcaNoDrifts_doublePrecDiag_and_Gca_maxIter1000.in"

srun "$BIN" "$INPUT"
