#!/bin/bash
#SBATCH --job-name=WeiNoEGCA1
#SBATCH --account=f202500196cpcaa3a
#SBATCH --partition=normal-arm
#SBATCH --time=0-24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=1

module purge
module load OpenMPI
ml HDF5/1.12.2-gompi-2022a
module load FFTW

BIN="$HOME/osiris_JCDev/bin/osiris-3D-gcaAllFeats.e"

srun "${BIN}" Gca.in
