#!/bin/bash
#SBATCH --job-name=MirrorRelBoris0_01
#SBATCH --account=f202500196cpcaa3a
#SBATCH --partition=normal-arm
#SBATCH --time=0-46:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=8

module purge
module load OpenMPI
ml HDF5/1.12.2-gompi-2022a
module load FFTW

BIN="$HOME/osiris_JCDev/bin/osiris-3D-gcaAllFeats.e"

srun "${BIN}" Boris.in
