#!/bin/bash
#SBATCH --job-name=Curv1stepgcaCorrNoBoris10
#SBATCH --account=f202500196cpcaa3a
#SBATCH --partition=normal-arm
#SBATCH --time=0-24:00:00
#SBATCH --nodes=1
#SBATCH --ntasks=8

module purge
module load OpenMPI
ml HDF5/1.12.2-gompi-2022a
module load FFTW

# ---- choose branch here ----
BRANCH="gcaCorrNoBoris"
WTBASE="$HOME/osiris_worktrees"

WORKTREE="$WTBASE/$BRANCH"

# ---- executable + input ----
EXE="osiris-3D-${BRANCH}.e"
BIN="$WORKTREE/bin/$EXE"
INPUT="gcaCorrNoBoris.in"

srun "$BIN" "$INPUT"
